// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import NODE_async_in_node from "./lessons/async-in-node.json";
import NODE_building_a_rest_api from "./lessons/building-a-rest-api.json";
import NODE_express_and_routing from "./lessons/express-and-routing.json";
import NODE_http_server from "./lessons/http-server.json";
import NODE_modules_and_npm from "./lessons/modules-and-npm.json";
import NODE_the_file_system from "./lessons/the-file-system.json";
import NODE_the_node_runtime from "./lessons/the-node-runtime.json";
import NODE_what_is_nodejs from "./lessons/what-is-nodejs.json";

export const RAW_NODE_LESSONS: Record<string, unknown> = {
  "async-in-node": NODE_async_in_node,
  "building-a-rest-api": NODE_building_a_rest_api,
  "express-and-routing": NODE_express_and_routing,
  "http-server": NODE_http_server,
  "modules-and-npm": NODE_modules_and_npm,
  "the-file-system": NODE_the_file_system,
  "the-node-runtime": NODE_the_node_runtime,
  "what-is-nodejs": NODE_what_is_nodejs,
};
