// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import NODEC_async_in_node from "./challenges/async-in-node.json";
import NODEC_building_a_rest_api from "./challenges/building-a-rest-api.json";
import NODEC_express_and_routing from "./challenges/express-and-routing.json";
import NODEC_http_server from "./challenges/http-server.json";
import NODEC_modules_and_npm from "./challenges/modules-and-npm.json";
import NODEC_the_file_system from "./challenges/the-file-system.json";
import NODEC_the_node_runtime from "./challenges/the-node-runtime.json";
import NODEC_what_is_nodejs from "./challenges/what-is-nodejs.json";

export const RAW_NODE_CHALLENGES: Record<string, unknown> = {
  "async-in-node": NODEC_async_in_node,
  "building-a-rest-api": NODEC_building_a_rest_api,
  "express-and-routing": NODEC_express_and_routing,
  "http-server": NODEC_http_server,
  "modules-and-npm": NODEC_modules_and_npm,
  "the-file-system": NODEC_the_file_system,
  "the-node-runtime": NODEC_the_node_runtime,
  "what-is-nodejs": NODEC_what_is_nodejs,
};
