// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import TS_basic_types from "./lessons/basic-types.json";
import TS_generics from "./lessons/generics.json";
import TS_interfaces_and_types from "./lessons/interfaces-and-types.json";
import TS_typescript_with_react from "./lessons/typescript-with-react.json";
import TS_typing_functions from "./lessons/typing-functions.json";
import TS_unions_and_narrowing from "./lessons/unions-and-narrowing.json";
import TS_what_is_typescript from "./lessons/what-is-typescript.json";

export const RAW_TS_LESSONS: Record<string, unknown> = {
  "basic-types": TS_basic_types,
  "generics": TS_generics,
  "interfaces-and-types": TS_interfaces_and_types,
  "typescript-with-react": TS_typescript_with_react,
  "typing-functions": TS_typing_functions,
  "unions-and-narrowing": TS_unions_and_narrowing,
  "what-is-typescript": TS_what_is_typescript,
};
