// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import TSC_basic_types from "./challenges/basic-types.json";
import TSC_generics from "./challenges/generics.json";
import TSC_interfaces_and_types from "./challenges/interfaces-and-types.json";
import TSC_typescript_with_react from "./challenges/typescript-with-react.json";
import TSC_typing_functions from "./challenges/typing-functions.json";
import TSC_unions_and_narrowing from "./challenges/unions-and-narrowing.json";
import TSC_what_is_typescript from "./challenges/what-is-typescript.json";

export const RAW_TS_CHALLENGES: Record<string, unknown> = {
  "basic-types": TSC_basic_types,
  "generics": TSC_generics,
  "interfaces-and-types": TSC_interfaces_and_types,
  "typescript-with-react": TSC_typescript_with_react,
  "typing-functions": TSC_typing_functions,
  "unions-and-narrowing": TSC_unions_and_narrowing,
  "what-is-typescript": TSC_what_is_typescript,
};
