// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import MCP_anatomy_of_a_tool_call from "./lessons/anatomy-of-a-tool-call.json";
import MCP_build_a_node_server from "./lessons/build-a-node-server.json";
import MCP_build_a_python_server from "./lessons/build-a-python-server.json";
import MCP_connect_to_a_host from "./lessons/connect-to-a-host.json";
import MCP_the_four_big_ideas from "./lessons/the-four-big-ideas.json";
import MCP_the_mcp_architecture from "./lessons/the-mcp-architecture.json";
import MCP_the_wire_protocol from "./lessons/the-wire-protocol.json";
import MCP_tools_resources_prompts from "./lessons/tools-resources-prompts.json";
import MCP_use_cases_and_safety from "./lessons/use-cases-and-safety.json";
import MCP_what_is_mcp from "./lessons/what-is-mcp.json";

export const RAW_MCP_LESSONS: Record<string, unknown> = {
  "anatomy-of-a-tool-call": MCP_anatomy_of_a_tool_call,
  "build-a-node-server": MCP_build_a_node_server,
  "build-a-python-server": MCP_build_a_python_server,
  "connect-to-a-host": MCP_connect_to_a_host,
  "the-four-big-ideas": MCP_the_four_big_ideas,
  "the-mcp-architecture": MCP_the_mcp_architecture,
  "the-wire-protocol": MCP_the_wire_protocol,
  "tools-resources-prompts": MCP_tools_resources_prompts,
  "use-cases-and-safety": MCP_use_cases_and_safety,
  "what-is-mcp": MCP_what_is_mcp,
};
