// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import MCPC_anatomy_of_a_tool_call from "./challenges/anatomy-of-a-tool-call.json";
import MCPC_build_a_node_server from "./challenges/build-a-node-server.json";
import MCPC_build_a_python_server from "./challenges/build-a-python-server.json";
import MCPC_connect_to_a_host from "./challenges/connect-to-a-host.json";
import MCPC_the_four_big_ideas from "./challenges/the-four-big-ideas.json";
import MCPC_the_mcp_architecture from "./challenges/the-mcp-architecture.json";
import MCPC_the_wire_protocol from "./challenges/the-wire-protocol.json";
import MCPC_tools_resources_prompts from "./challenges/tools-resources-prompts.json";
import MCPC_use_cases_and_safety from "./challenges/use-cases-and-safety.json";
import MCPC_what_is_mcp from "./challenges/what-is-mcp.json";

export const RAW_MCP_CHALLENGES: Record<string, unknown> = {
  "anatomy-of-a-tool-call": MCPC_anatomy_of_a_tool_call,
  "build-a-node-server": MCPC_build_a_node_server,
  "build-a-python-server": MCPC_build_a_python_server,
  "connect-to-a-host": MCPC_connect_to_a_host,
  "the-four-big-ideas": MCPC_the_four_big_ideas,
  "the-mcp-architecture": MCPC_the_mcp_architecture,
  "the-wire-protocol": MCPC_the_wire_protocol,
  "tools-resources-prompts": MCPC_tools_resources_prompts,
  "use-cases-and-safety": MCPC_use_cases_and_safety,
  "what-is-mcp": MCPC_what_is_mcp,
};
