// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import JSC_arrays from "./challenges/arrays.json";
import JSC_arrow_functions from "./challenges/arrow-functions.json";
import JSC_classes from "./challenges/classes.json";
import JSC_conditionals from "./challenges/conditionals.json";
import JSC_destructuring_and_spread from "./challenges/destructuring-and-spread.json";
import JSC_encapsulation from "./challenges/encapsulation.json";
import JSC_error_handling from "./challenges/error-handling.json";
import JSC_es_modules from "./challenges/es-modules.json";
import JSC_events_and_listeners from "./challenges/events-and-listeners.json";
import JSC_higher_order_functions from "./challenges/higher-order-functions.json";
import JSC_inheritance_and_polymorphism from "./challenges/inheritance-and-polymorphism.json";
import JSC_javascript_functions from "./challenges/javascript-functions.json";
import JSC_loops from "./challenges/loops.json";
import JSC_objects from "./challenges/objects.json";
import JSC_operators_and_expressions from "./challenges/operators-and-expressions.json";
import JSC_promises_and_async from "./challenges/promises-and-async.json";
import JSC_the_dom from "./challenges/the-dom.json";
import JSC_the_event_loop from "./challenges/the-event-loop.json";
import JSC_typescript_basics from "./challenges/typescript-basics.json";
import JSC_typescript_generics from "./challenges/typescript-generics.json";
import JSC_typescript_interfaces from "./challenges/typescript-interfaces.json";
import JSC_variables_and_data_types from "./challenges/variables-and-data-types.json";
import JSC_what_is_javascript from "./challenges/what-is-javascript.json";

export const RAW_JS_CHALLENGES: Record<string, unknown> = {
  "arrays": JSC_arrays,
  "arrow-functions": JSC_arrow_functions,
  "classes": JSC_classes,
  "conditionals": JSC_conditionals,
  "destructuring-and-spread": JSC_destructuring_and_spread,
  "encapsulation": JSC_encapsulation,
  "error-handling": JSC_error_handling,
  "es-modules": JSC_es_modules,
  "events-and-listeners": JSC_events_and_listeners,
  "higher-order-functions": JSC_higher_order_functions,
  "inheritance-and-polymorphism": JSC_inheritance_and_polymorphism,
  "javascript-functions": JSC_javascript_functions,
  "loops": JSC_loops,
  "objects": JSC_objects,
  "operators-and-expressions": JSC_operators_and_expressions,
  "promises-and-async": JSC_promises_and_async,
  "the-dom": JSC_the_dom,
  "the-event-loop": JSC_the_event_loop,
  "typescript-basics": JSC_typescript_basics,
  "typescript-generics": JSC_typescript_generics,
  "typescript-interfaces": JSC_typescript_interfaces,
  "variables-and-data-types": JSC_variables_and_data_types,
  "what-is-javascript": JSC_what_is_javascript,
};
