// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import JS_arrays from "./lessons/arrays.json";
import JS_arrow_functions from "./lessons/arrow-functions.json";
import JS_classes from "./lessons/classes.json";
import JS_conditionals from "./lessons/conditionals.json";
import JS_destructuring_and_spread from "./lessons/destructuring-and-spread.json";
import JS_encapsulation from "./lessons/encapsulation.json";
import JS_error_handling from "./lessons/error-handling.json";
import JS_es_modules from "./lessons/es-modules.json";
import JS_events_and_listeners from "./lessons/events-and-listeners.json";
import JS_higher_order_functions from "./lessons/higher-order-functions.json";
import JS_inheritance_and_polymorphism from "./lessons/inheritance-and-polymorphism.json";
import JS_javascript_functions from "./lessons/javascript-functions.json";
import JS_loops from "./lessons/loops.json";
import JS_objects from "./lessons/objects.json";
import JS_operators_and_expressions from "./lessons/operators-and-expressions.json";
import JS_promises_and_async from "./lessons/promises-and-async.json";
import JS_the_dom from "./lessons/the-dom.json";
import JS_the_event_loop from "./lessons/the-event-loop.json";
import JS_typescript_basics from "./lessons/typescript-basics.json";
import JS_typescript_generics from "./lessons/typescript-generics.json";
import JS_typescript_interfaces from "./lessons/typescript-interfaces.json";
import JS_variables_and_data_types from "./lessons/variables-and-data-types.json";
import JS_what_is_javascript from "./lessons/what-is-javascript.json";

export const RAW_JS_LESSONS: Record<string, unknown> = {
  "arrays": JS_arrays,
  "arrow-functions": JS_arrow_functions,
  "classes": JS_classes,
  "conditionals": JS_conditionals,
  "destructuring-and-spread": JS_destructuring_and_spread,
  "encapsulation": JS_encapsulation,
  "error-handling": JS_error_handling,
  "es-modules": JS_es_modules,
  "events-and-listeners": JS_events_and_listeners,
  "higher-order-functions": JS_higher_order_functions,
  "inheritance-and-polymorphism": JS_inheritance_and_polymorphism,
  "javascript-functions": JS_javascript_functions,
  "loops": JS_loops,
  "objects": JS_objects,
  "operators-and-expressions": JS_operators_and_expressions,
  "promises-and-async": JS_promises_and_async,
  "the-dom": JS_the_dom,
  "the-event-loop": JS_the_event_loop,
  "typescript-basics": JS_typescript_basics,
  "typescript-generics": JS_typescript_generics,
  "typescript-interfaces": JS_typescript_interfaces,
  "variables-and-data-types": JS_variables_and_data_types,
  "what-is-javascript": JS_what_is_javascript,
};
