// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import JSC_arrays from "./challenges/arrays.json";
import JSC_conditionals from "./challenges/conditionals.json";
import JSC_events_and_listeners from "./challenges/events-and-listeners.json";
import JSC_javascript_functions from "./challenges/javascript-functions.json";
import JSC_loops from "./challenges/loops.json";
import JSC_objects from "./challenges/objects.json";
import JSC_operators_and_expressions from "./challenges/operators-and-expressions.json";
import JSC_promises_and_async from "./challenges/promises-and-async.json";
import JSC_the_dom from "./challenges/the-dom.json";
import JSC_the_event_loop from "./challenges/the-event-loop.json";
import JSC_variables_and_data_types from "./challenges/variables-and-data-types.json";
import JSC_what_is_javascript from "./challenges/what-is-javascript.json";

export const RAW_JS_CHALLENGES: Record<string, unknown> = {
  "arrays": JSC_arrays,
  "conditionals": JSC_conditionals,
  "events-and-listeners": JSC_events_and_listeners,
  "javascript-functions": JSC_javascript_functions,
  "loops": JSC_loops,
  "objects": JSC_objects,
  "operators-and-expressions": JSC_operators_and_expressions,
  "promises-and-async": JSC_promises_and_async,
  "the-dom": JSC_the_dom,
  "the-event-loop": JSC_the_event_loop,
  "variables-and-data-types": JSC_variables_and_data_types,
  "what-is-javascript": JSC_what_is_javascript,
};
