// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import JS_arrays from "./lessons/arrays.json";
import JS_conditionals from "./lessons/conditionals.json";
import JS_events_and_listeners from "./lessons/events-and-listeners.json";
import JS_javascript_functions from "./lessons/javascript-functions.json";
import JS_loops from "./lessons/loops.json";
import JS_objects from "./lessons/objects.json";
import JS_operators_and_expressions from "./lessons/operators-and-expressions.json";
import JS_promises_and_async from "./lessons/promises-and-async.json";
import JS_the_dom from "./lessons/the-dom.json";
import JS_the_event_loop from "./lessons/the-event-loop.json";
import JS_variables_and_data_types from "./lessons/variables-and-data-types.json";
import JS_what_is_javascript from "./lessons/what-is-javascript.json";

export const RAW_JS_LESSONS: Record<string, unknown> = {
  "arrays": JS_arrays,
  "conditionals": JS_conditionals,
  "events-and-listeners": JS_events_and_listeners,
  "javascript-functions": JS_javascript_functions,
  "loops": JS_loops,
  "objects": JS_objects,
  "operators-and-expressions": JS_operators_and_expressions,
  "promises-and-async": JS_promises_and_async,
  "the-dom": JS_the_dom,
  "the-event-loop": JS_the_event_loop,
  "variables-and-data-types": JS_variables_and_data_types,
  "what-is-javascript": JS_what_is_javascript,
};
