// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import LLMC_attention from "./challenges/attention.json";
import LLMC_context_windows from "./challenges/context-windows.json";
import LLMC_embeddings from "./challenges/embeddings.json";
import LLMC_fine_tuning_and_rlhf from "./challenges/fine-tuning-and-rlhf.json";
import LLMC_how_llms_are_trained from "./challenges/how-llms-are-trained.json";
import LLMC_limitations_and_hallucinations from "./challenges/limitations-and-hallucinations.json";
import LLMC_next_token_prediction from "./challenges/next-token-prediction.json";
import LLMC_prompting_and_in_context_learning from "./challenges/prompting-and-in-context-learning.json";
import LLMC_sampling_and_temperature from "./challenges/sampling-and-temperature.json";
import LLMC_the_transformer from "./challenges/the-transformer.json";
import LLMC_tokens_and_tokenization from "./challenges/tokens-and-tokenization.json";
import LLMC_what_is_an_llm from "./challenges/what-is-an-llm.json";

export const RAW_LLM_CHALLENGES: Record<string, unknown> = {
  "attention": LLMC_attention,
  "context-windows": LLMC_context_windows,
  "embeddings": LLMC_embeddings,
  "fine-tuning-and-rlhf": LLMC_fine_tuning_and_rlhf,
  "how-llms-are-trained": LLMC_how_llms_are_trained,
  "limitations-and-hallucinations": LLMC_limitations_and_hallucinations,
  "next-token-prediction": LLMC_next_token_prediction,
  "prompting-and-in-context-learning": LLMC_prompting_and_in_context_learning,
  "sampling-and-temperature": LLMC_sampling_and_temperature,
  "the-transformer": LLMC_the_transformer,
  "tokens-and-tokenization": LLMC_tokens_and_tokenization,
  "what-is-an-llm": LLMC_what_is_an_llm,
};
