// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import LLM_attention from "./lessons/attention.json";
import LLM_context_windows from "./lessons/context-windows.json";
import LLM_embeddings from "./lessons/embeddings.json";
import LLM_fine_tuning_and_rlhf from "./lessons/fine-tuning-and-rlhf.json";
import LLM_how_llms_are_trained from "./lessons/how-llms-are-trained.json";
import LLM_limitations_and_hallucinations from "./lessons/limitations-and-hallucinations.json";
import LLM_next_token_prediction from "./lessons/next-token-prediction.json";
import LLM_prompting_and_in_context_learning from "./lessons/prompting-and-in-context-learning.json";
import LLM_sampling_and_temperature from "./lessons/sampling-and-temperature.json";
import LLM_the_transformer from "./lessons/the-transformer.json";
import LLM_tokens_and_tokenization from "./lessons/tokens-and-tokenization.json";
import LLM_what_is_an_llm from "./lessons/what-is-an-llm.json";

export const RAW_LLM_LESSONS: Record<string, unknown> = {
  "attention": LLM_attention,
  "context-windows": LLM_context_windows,
  "embeddings": LLM_embeddings,
  "fine-tuning-and-rlhf": LLM_fine_tuning_and_rlhf,
  "how-llms-are-trained": LLM_how_llms_are_trained,
  "limitations-and-hallucinations": LLM_limitations_and_hallucinations,
  "next-token-prediction": LLM_next_token_prediction,
  "prompting-and-in-context-learning": LLM_prompting_and_in_context_learning,
  "sampling-and-temperature": LLM_sampling_and_temperature,
  "the-transformer": LLM_the_transformer,
  "tokens-and-tokenization": LLM_tokens_and_tokenization,
  "what-is-an-llm": LLM_what_is_an_llm,
};
