// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import S_args_kwargs from "./slides/args-kwargs.json";
import S_arithmetic_operators from "./slides/arithmetic-operators.json";
import S_assignment_operators from "./slides/assignment-operators.json";
import S_booleans_and_none from "./slides/booleans-and-none.json";
import S_break_continue_pass from "./slides/break-continue-pass.json";
import S_builtin_tools from "./slides/builtin-tools.json";
import S_classes_and_objects from "./slides/classes-and-objects.json";
import S_closures from "./slides/closures.json";
import S_comments from "./slides/comments.json";
import S_comparison_operators from "./slides/comparison-operators.json";
import S_context_managers from "./slides/context-managers.json";
import S_data_types from "./slides/data-types.json";
import S_decorators from "./slides/decorators.json";
import S_defining_functions from "./slides/defining-functions.json";
import S_dictionaries from "./slides/dictionaries.json";
import S_dunder_methods from "./slides/dunder-methods.json";
import S_encapsulation from "./slides/encapsulation.json";
import S_exceptions from "./slides/exceptions.json";
import S_for_loops from "./slides/for-loops.json";
import S_function_arguments from "./slides/function-arguments.json";
import S_generators from "./slides/generators.json";
import S_hello_world from "./slides/hello-world.json";
import S_how_python_works from "./slides/how-python-works.json";
import S_if_statements from "./slides/if-statements.json";
import S_inheritance from "./slides/inheritance.json";
import S_input_output from "./slides/input-output.json";
import S_installing_python from "./slides/installing-python.json";
import S_iterators from "./slides/iterators.json";
import S_lambda_functions from "./slides/lambda-functions.json";
import S_list_comprehensions from "./slides/list-comprehensions.json";
import S_lists from "./slides/lists.json";
import S_logical_operators from "./slides/logical-operators.json";
import S_match_statements from "./slides/match-statements.json";
import S_modules_and_imports from "./slides/modules-and-imports.json";
import S_numbers from "./slides/numbers.json";
import S_operator_precedence from "./slides/operator-precedence.json";
import S_pep8_and_style from "./slides/pep8-and-style.json";
import S_pip_and_packages from "./slides/pip-and-packages.json";
import S_polymorphism from "./slides/polymorphism.json";
import S_popular_libraries from "./slides/popular-libraries.json";
import S_raising_and_custom_exceptions from "./slides/raising-and-custom-exceptions.json";
import S_reading_writing_files from "./slides/reading-writing-files.json";
import S_recursion from "./slides/recursion.json";
import S_regular_expressions from "./slides/regular-expressions.json";
import S_return_values from "./slides/return-values.json";
import S_sets from "./slides/sets.json";
import S_string_formatting from "./slides/string-formatting.json";
import S_string_methods from "./slides/string-methods.json";
import S_string_slicing from "./slides/string-slicing.json";
import S_strings_basics from "./slides/strings-basics.json";
import S_the_init_method from "./slides/the-init-method.json";
import S_the_repl from "./slides/the-repl.json";
import S_the_standard_library from "./slides/the-standard-library.json";
import S_tuples from "./slides/tuples.json";
import S_type_conversion from "./slides/type-conversion.json";
import S_type_hints from "./slides/type-hints.json";
import S_variable_scope from "./slides/variable-scope.json";
import S_variables from "./slides/variables.json";
import S_virtual_environments from "./slides/virtual-environments.json";
import S_what_is_python from "./slides/what-is-python.json";
import S_while_loops from "./slides/while-loops.json";
import S_working_with_json from "./slides/working-with-json.json";
import S_your_next_steps from "./slides/your-next-steps.json";

export const RAW_SLIDES: Record<string, unknown> = {
  "args-kwargs": S_args_kwargs,
  "arithmetic-operators": S_arithmetic_operators,
  "assignment-operators": S_assignment_operators,
  "booleans-and-none": S_booleans_and_none,
  "break-continue-pass": S_break_continue_pass,
  "builtin-tools": S_builtin_tools,
  "classes-and-objects": S_classes_and_objects,
  "closures": S_closures,
  "comments": S_comments,
  "comparison-operators": S_comparison_operators,
  "context-managers": S_context_managers,
  "data-types": S_data_types,
  "decorators": S_decorators,
  "defining-functions": S_defining_functions,
  "dictionaries": S_dictionaries,
  "dunder-methods": S_dunder_methods,
  "encapsulation": S_encapsulation,
  "exceptions": S_exceptions,
  "for-loops": S_for_loops,
  "function-arguments": S_function_arguments,
  "generators": S_generators,
  "hello-world": S_hello_world,
  "how-python-works": S_how_python_works,
  "if-statements": S_if_statements,
  "inheritance": S_inheritance,
  "input-output": S_input_output,
  "installing-python": S_installing_python,
  "iterators": S_iterators,
  "lambda-functions": S_lambda_functions,
  "list-comprehensions": S_list_comprehensions,
  "lists": S_lists,
  "logical-operators": S_logical_operators,
  "match-statements": S_match_statements,
  "modules-and-imports": S_modules_and_imports,
  "numbers": S_numbers,
  "operator-precedence": S_operator_precedence,
  "pep8-and-style": S_pep8_and_style,
  "pip-and-packages": S_pip_and_packages,
  "polymorphism": S_polymorphism,
  "popular-libraries": S_popular_libraries,
  "raising-and-custom-exceptions": S_raising_and_custom_exceptions,
  "reading-writing-files": S_reading_writing_files,
  "recursion": S_recursion,
  "regular-expressions": S_regular_expressions,
  "return-values": S_return_values,
  "sets": S_sets,
  "string-formatting": S_string_formatting,
  "string-methods": S_string_methods,
  "string-slicing": S_string_slicing,
  "strings-basics": S_strings_basics,
  "the-init-method": S_the_init_method,
  "the-repl": S_the_repl,
  "the-standard-library": S_the_standard_library,
  "tuples": S_tuples,
  "type-conversion": S_type_conversion,
  "type-hints": S_type_hints,
  "variable-scope": S_variable_scope,
  "variables": S_variables,
  "virtual-environments": S_virtual_environments,
  "what-is-python": S_what_is_python,
  "while-loops": S_while_loops,
  "working-with-json": S_working_with_json,
  "your-next-steps": S_your_next_steps,
};
