// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import L_args_kwargs from "./lessons/args-kwargs.json";
import L_arithmetic_operators from "./lessons/arithmetic-operators.json";
import L_assignment_operators from "./lessons/assignment-operators.json";
import L_booleans_and_none from "./lessons/booleans-and-none.json";
import L_break_continue_pass from "./lessons/break-continue-pass.json";
import L_builtin_tools from "./lessons/builtin-tools.json";
import L_class_and_static_methods from "./lessons/class-and-static-methods.json";
import L_classes_and_objects from "./lessons/classes-and-objects.json";
import L_closures from "./lessons/closures.json";
import L_comments from "./lessons/comments.json";
import L_comparison_operators from "./lessons/comparison-operators.json";
import L_context_managers from "./lessons/context-managers.json";
import L_data_types from "./lessons/data-types.json";
import L_dataclasses from "./lessons/dataclasses.json";
import L_decorators from "./lessons/decorators.json";
import L_defining_functions from "./lessons/defining-functions.json";
import L_dictionaries from "./lessons/dictionaries.json";
import L_dunder_methods from "./lessons/dunder-methods.json";
import L_encapsulation from "./lessons/encapsulation.json";
import L_exceptions from "./lessons/exceptions.json";
import L_for_loops from "./lessons/for-loops.json";
import L_function_arguments from "./lessons/function-arguments.json";
import L_generators from "./lessons/generators.json";
import L_hello_world from "./lessons/hello-world.json";
import L_how_python_works from "./lessons/how-python-works.json";
import L_if_statements from "./lessons/if-statements.json";
import L_inheritance from "./lessons/inheritance.json";
import L_input_output from "./lessons/input-output.json";
import L_installing_python from "./lessons/installing-python.json";
import L_iterators from "./lessons/iterators.json";
import L_lambda_functions from "./lessons/lambda-functions.json";
import L_list_comprehensions from "./lessons/list-comprehensions.json";
import L_lists from "./lessons/lists.json";
import L_logical_operators from "./lessons/logical-operators.json";
import L_match_statements from "./lessons/match-statements.json";
import L_modules_and_imports from "./lessons/modules-and-imports.json";
import L_numbers from "./lessons/numbers.json";
import L_operator_precedence from "./lessons/operator-precedence.json";
import L_pep8_and_style from "./lessons/pep8-and-style.json";
import L_pip_and_packages from "./lessons/pip-and-packages.json";
import L_polymorphism from "./lessons/polymorphism.json";
import L_popular_libraries from "./lessons/popular-libraries.json";
import L_properties from "./lessons/properties.json";
import L_raising_and_custom_exceptions from "./lessons/raising-and-custom-exceptions.json";
import L_reading_writing_files from "./lessons/reading-writing-files.json";
import L_recursion from "./lessons/recursion.json";
import L_regular_expressions from "./lessons/regular-expressions.json";
import L_return_values from "./lessons/return-values.json";
import L_sets from "./lessons/sets.json";
import L_string_formatting from "./lessons/string-formatting.json";
import L_string_methods from "./lessons/string-methods.json";
import L_string_slicing from "./lessons/string-slicing.json";
import L_strings_basics from "./lessons/strings-basics.json";
import L_the_init_method from "./lessons/the-init-method.json";
import L_the_repl from "./lessons/the-repl.json";
import L_the_standard_library from "./lessons/the-standard-library.json";
import L_tuples from "./lessons/tuples.json";
import L_type_conversion from "./lessons/type-conversion.json";
import L_type_hints from "./lessons/type-hints.json";
import L_variable_scope from "./lessons/variable-scope.json";
import L_variables from "./lessons/variables.json";
import L_virtual_environments from "./lessons/virtual-environments.json";
import L_what_is_python from "./lessons/what-is-python.json";
import L_while_loops from "./lessons/while-loops.json";
import L_working_with_json from "./lessons/working-with-json.json";
import L_your_next_steps from "./lessons/your-next-steps.json";

export const RAW_LESSONS: Record<string, unknown> = {
  "args-kwargs": L_args_kwargs,
  "arithmetic-operators": L_arithmetic_operators,
  "assignment-operators": L_assignment_operators,
  "booleans-and-none": L_booleans_and_none,
  "break-continue-pass": L_break_continue_pass,
  "builtin-tools": L_builtin_tools,
  "class-and-static-methods": L_class_and_static_methods,
  "classes-and-objects": L_classes_and_objects,
  "closures": L_closures,
  "comments": L_comments,
  "comparison-operators": L_comparison_operators,
  "context-managers": L_context_managers,
  "data-types": L_data_types,
  "dataclasses": L_dataclasses,
  "decorators": L_decorators,
  "defining-functions": L_defining_functions,
  "dictionaries": L_dictionaries,
  "dunder-methods": L_dunder_methods,
  "encapsulation": L_encapsulation,
  "exceptions": L_exceptions,
  "for-loops": L_for_loops,
  "function-arguments": L_function_arguments,
  "generators": L_generators,
  "hello-world": L_hello_world,
  "how-python-works": L_how_python_works,
  "if-statements": L_if_statements,
  "inheritance": L_inheritance,
  "input-output": L_input_output,
  "installing-python": L_installing_python,
  "iterators": L_iterators,
  "lambda-functions": L_lambda_functions,
  "list-comprehensions": L_list_comprehensions,
  "lists": L_lists,
  "logical-operators": L_logical_operators,
  "match-statements": L_match_statements,
  "modules-and-imports": L_modules_and_imports,
  "numbers": L_numbers,
  "operator-precedence": L_operator_precedence,
  "pep8-and-style": L_pep8_and_style,
  "pip-and-packages": L_pip_and_packages,
  "polymorphism": L_polymorphism,
  "popular-libraries": L_popular_libraries,
  "properties": L_properties,
  "raising-and-custom-exceptions": L_raising_and_custom_exceptions,
  "reading-writing-files": L_reading_writing_files,
  "recursion": L_recursion,
  "regular-expressions": L_regular_expressions,
  "return-values": L_return_values,
  "sets": L_sets,
  "string-formatting": L_string_formatting,
  "string-methods": L_string_methods,
  "string-slicing": L_string_slicing,
  "strings-basics": L_strings_basics,
  "the-init-method": L_the_init_method,
  "the-repl": L_the_repl,
  "the-standard-library": L_the_standard_library,
  "tuples": L_tuples,
  "type-conversion": L_type_conversion,
  "type-hints": L_type_hints,
  "variable-scope": L_variable_scope,
  "variables": L_variables,
  "virtual-environments": L_virtual_environments,
  "what-is-python": L_what_is_python,
  "while-loops": L_while_loops,
  "working-with-json": L_working_with_json,
  "your-next-steps": L_your_next_steps,
};
