// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import C_args_kwargs from "./challenges/args-kwargs.json";
import C_arithmetic_operators from "./challenges/arithmetic-operators.json";
import C_assignment_operators from "./challenges/assignment-operators.json";
import C_booleans_and_none from "./challenges/booleans-and-none.json";
import C_break_continue_pass from "./challenges/break-continue-pass.json";
import C_builtin_tools from "./challenges/builtin-tools.json";
import C_classes_and_objects from "./challenges/classes-and-objects.json";
import C_closures from "./challenges/closures.json";
import C_comments from "./challenges/comments.json";
import C_comparison_operators from "./challenges/comparison-operators.json";
import C_context_managers from "./challenges/context-managers.json";
import C_data_types from "./challenges/data-types.json";
import C_decorators from "./challenges/decorators.json";
import C_defining_functions from "./challenges/defining-functions.json";
import C_dictionaries from "./challenges/dictionaries.json";
import C_dunder_methods from "./challenges/dunder-methods.json";
import C_encapsulation from "./challenges/encapsulation.json";
import C_exceptions from "./challenges/exceptions.json";
import C_for_loops from "./challenges/for-loops.json";
import C_function_arguments from "./challenges/function-arguments.json";
import C_generators from "./challenges/generators.json";
import C_hello_world from "./challenges/hello-world.json";
import C_how_python_works from "./challenges/how-python-works.json";
import C_if_statements from "./challenges/if-statements.json";
import C_inheritance from "./challenges/inheritance.json";
import C_input_output from "./challenges/input-output.json";
import C_installing_python from "./challenges/installing-python.json";
import C_iterators from "./challenges/iterators.json";
import C_lambda_functions from "./challenges/lambda-functions.json";
import C_list_comprehensions from "./challenges/list-comprehensions.json";
import C_lists from "./challenges/lists.json";
import C_logical_operators from "./challenges/logical-operators.json";
import C_match_statements from "./challenges/match-statements.json";
import C_modules_and_imports from "./challenges/modules-and-imports.json";
import C_numbers from "./challenges/numbers.json";
import C_operator_precedence from "./challenges/operator-precedence.json";
import C_pep8_and_style from "./challenges/pep8-and-style.json";
import C_pip_and_packages from "./challenges/pip-and-packages.json";
import C_polymorphism from "./challenges/polymorphism.json";
import C_popular_libraries from "./challenges/popular-libraries.json";
import C_raising_and_custom_exceptions from "./challenges/raising-and-custom-exceptions.json";
import C_reading_writing_files from "./challenges/reading-writing-files.json";
import C_recursion from "./challenges/recursion.json";
import C_regular_expressions from "./challenges/regular-expressions.json";
import C_return_values from "./challenges/return-values.json";
import C_sets from "./challenges/sets.json";
import C_string_formatting from "./challenges/string-formatting.json";
import C_string_methods from "./challenges/string-methods.json";
import C_string_slicing from "./challenges/string-slicing.json";
import C_strings_basics from "./challenges/strings-basics.json";
import C_the_init_method from "./challenges/the-init-method.json";
import C_the_repl from "./challenges/the-repl.json";
import C_the_standard_library from "./challenges/the-standard-library.json";
import C_tuples from "./challenges/tuples.json";
import C_type_conversion from "./challenges/type-conversion.json";
import C_type_hints from "./challenges/type-hints.json";
import C_variable_scope from "./challenges/variable-scope.json";
import C_variables from "./challenges/variables.json";
import C_virtual_environments from "./challenges/virtual-environments.json";
import C_what_is_python from "./challenges/what-is-python.json";
import C_while_loops from "./challenges/while-loops.json";
import C_working_with_json from "./challenges/working-with-json.json";
import C_your_next_steps from "./challenges/your-next-steps.json";

export const RAW_CHALLENGES: Record<string, unknown> = {
  "args-kwargs": C_args_kwargs,
  "arithmetic-operators": C_arithmetic_operators,
  "assignment-operators": C_assignment_operators,
  "booleans-and-none": C_booleans_and_none,
  "break-continue-pass": C_break_continue_pass,
  "builtin-tools": C_builtin_tools,
  "classes-and-objects": C_classes_and_objects,
  "closures": C_closures,
  "comments": C_comments,
  "comparison-operators": C_comparison_operators,
  "context-managers": C_context_managers,
  "data-types": C_data_types,
  "decorators": C_decorators,
  "defining-functions": C_defining_functions,
  "dictionaries": C_dictionaries,
  "dunder-methods": C_dunder_methods,
  "encapsulation": C_encapsulation,
  "exceptions": C_exceptions,
  "for-loops": C_for_loops,
  "function-arguments": C_function_arguments,
  "generators": C_generators,
  "hello-world": C_hello_world,
  "how-python-works": C_how_python_works,
  "if-statements": C_if_statements,
  "inheritance": C_inheritance,
  "input-output": C_input_output,
  "installing-python": C_installing_python,
  "iterators": C_iterators,
  "lambda-functions": C_lambda_functions,
  "list-comprehensions": C_list_comprehensions,
  "lists": C_lists,
  "logical-operators": C_logical_operators,
  "match-statements": C_match_statements,
  "modules-and-imports": C_modules_and_imports,
  "numbers": C_numbers,
  "operator-precedence": C_operator_precedence,
  "pep8-and-style": C_pep8_and_style,
  "pip-and-packages": C_pip_and_packages,
  "polymorphism": C_polymorphism,
  "popular-libraries": C_popular_libraries,
  "raising-and-custom-exceptions": C_raising_and_custom_exceptions,
  "reading-writing-files": C_reading_writing_files,
  "recursion": C_recursion,
  "regular-expressions": C_regular_expressions,
  "return-values": C_return_values,
  "sets": C_sets,
  "string-formatting": C_string_formatting,
  "string-methods": C_string_methods,
  "string-slicing": C_string_slicing,
  "strings-basics": C_strings_basics,
  "the-init-method": C_the_init_method,
  "the-repl": C_the_repl,
  "the-standard-library": C_the_standard_library,
  "tuples": C_tuples,
  "type-conversion": C_type_conversion,
  "type-hints": C_type_hints,
  "variable-scope": C_variable_scope,
  "variables": C_variables,
  "virtual-environments": C_virtual_environments,
  "what-is-python": C_what_is_python,
  "while-loops": C_while_loops,
  "working-with-json": C_working_with_json,
  "your-next-steps": C_your_next_steps,
};
