// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import AIC_a_star_search from "./challenges/a-star-search.json";
import AIC_ai_ethics_and_future from "./challenges/ai-ethics-and-future.json";
import AIC_alpha_beta_pruning from "./challenges/alpha-beta-pruning.json";
import AIC_bfs_and_dfs from "./challenges/bfs-and-dfs.json";
import AIC_computer_vision from "./challenges/computer-vision.json";
import AIC_history_of_ai from "./challenges/history-of-ai.json";
import AIC_how_networks_learn from "./challenges/how-networks-learn.json";
import AIC_intelligent_agents from "./challenges/intelligent-agents.json";
import AIC_minimax from "./challenges/minimax.json";
import AIC_neural_networks_and_deep_learning from "./challenges/neural-networks-and-deep-learning.json";
import AIC_nlp_and_llms from "./challenges/nlp-and-llms.json";
import AIC_problem_solving_as_search from "./challenges/problem-solving-as-search.json";
import AIC_the_perceptron from "./challenges/the-perceptron.json";
import AIC_what_is_ai from "./challenges/what-is-ai.json";

export const RAW_AI_CHALLENGES: Record<string, unknown> = {
  "a-star-search": AIC_a_star_search,
  "ai-ethics-and-future": AIC_ai_ethics_and_future,
  "alpha-beta-pruning": AIC_alpha_beta_pruning,
  "bfs-and-dfs": AIC_bfs_and_dfs,
  "computer-vision": AIC_computer_vision,
  "history-of-ai": AIC_history_of_ai,
  "how-networks-learn": AIC_how_networks_learn,
  "intelligent-agents": AIC_intelligent_agents,
  "minimax": AIC_minimax,
  "neural-networks-and-deep-learning": AIC_neural_networks_and_deep_learning,
  "nlp-and-llms": AIC_nlp_and_llms,
  "problem-solving-as-search": AIC_problem_solving_as_search,
  "the-perceptron": AIC_the_perceptron,
  "what-is-ai": AIC_what_is_ai,
};
