// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import AI_a_star_search from "./lessons/a-star-search.json";
import AI_ai_ethics_and_future from "./lessons/ai-ethics-and-future.json";
import AI_alpha_beta_pruning from "./lessons/alpha-beta-pruning.json";
import AI_bfs_and_dfs from "./lessons/bfs-and-dfs.json";
import AI_computer_vision from "./lessons/computer-vision.json";
import AI_history_of_ai from "./lessons/history-of-ai.json";
import AI_how_networks_learn from "./lessons/how-networks-learn.json";
import AI_intelligent_agents from "./lessons/intelligent-agents.json";
import AI_minimax from "./lessons/minimax.json";
import AI_neural_networks_and_deep_learning from "./lessons/neural-networks-and-deep-learning.json";
import AI_nlp_and_llms from "./lessons/nlp-and-llms.json";
import AI_problem_solving_as_search from "./lessons/problem-solving-as-search.json";
import AI_the_perceptron from "./lessons/the-perceptron.json";
import AI_what_is_ai from "./lessons/what-is-ai.json";

export const RAW_AI_LESSONS: Record<string, unknown> = {
  "a-star-search": AI_a_star_search,
  "ai-ethics-and-future": AI_ai_ethics_and_future,
  "alpha-beta-pruning": AI_alpha_beta_pruning,
  "bfs-and-dfs": AI_bfs_and_dfs,
  "computer-vision": AI_computer_vision,
  "history-of-ai": AI_history_of_ai,
  "how-networks-learn": AI_how_networks_learn,
  "intelligent-agents": AI_intelligent_agents,
  "minimax": AI_minimax,
  "neural-networks-and-deep-learning": AI_neural_networks_and_deep_learning,
  "nlp-and-llms": AI_nlp_and_llms,
  "problem-solving-as-search": AI_problem_solving_as_search,
  "the-perceptron": AI_the_perceptron,
  "what-is-ai": AI_what_is_ai,
};
