// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import CSSC_cascade_and_specificity from "./challenges/cascade-and-specificity.json";
import CSSC_colors_and_units from "./challenges/colors-and-units.json";
import CSSC_css_grid from "./challenges/css-grid.json";
import CSSC_css_selectors from "./challenges/css-selectors.json";
import CSSC_flexbox from "./challenges/flexbox.json";
import CSSC_responsive_design from "./challenges/responsive-design.json";
import CSSC_the_box_model from "./challenges/the-box-model.json";
import CSSC_transitions_and_animations from "./challenges/transitions-and-animations.json";
import CSSC_what_is_css from "./challenges/what-is-css.json";

export const RAW_CSS_CHALLENGES: Record<string, unknown> = {
  "cascade-and-specificity": CSSC_cascade_and_specificity,
  "colors-and-units": CSSC_colors_and_units,
  "css-grid": CSSC_css_grid,
  "css-selectors": CSSC_css_selectors,
  "flexbox": CSSC_flexbox,
  "responsive-design": CSSC_responsive_design,
  "the-box-model": CSSC_the_box_model,
  "transitions-and-animations": CSSC_transitions_and_animations,
  "what-is-css": CSSC_what_is_css,
};
