// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import CSS_cascade_and_specificity from "./lessons/cascade-and-specificity.json";
import CSS_colors_and_units from "./lessons/colors-and-units.json";
import CSS_css_grid from "./lessons/css-grid.json";
import CSS_css_selectors from "./lessons/css-selectors.json";
import CSS_flexbox from "./lessons/flexbox.json";
import CSS_responsive_design from "./lessons/responsive-design.json";
import CSS_the_box_model from "./lessons/the-box-model.json";
import CSS_transitions_and_animations from "./lessons/transitions-and-animations.json";
import CSS_what_is_css from "./lessons/what-is-css.json";

export const RAW_CSS_LESSONS: Record<string, unknown> = {
  "cascade-and-specificity": CSS_cascade_and_specificity,
  "colors-and-units": CSS_colors_and_units,
  "css-grid": CSS_css_grid,
  "css-selectors": CSS_css_selectors,
  "flexbox": CSS_flexbox,
  "responsive-design": CSS_responsive_design,
  "the-box-model": CSS_the_box_model,
  "transitions-and-animations": CSS_transitions_and_animations,
  "what-is-css": CSS_what_is_css,
};
