// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import MLC_data_and_features from "./challenges/data-and-features.json";
import MLC_decision_trees from "./challenges/decision-trees.json";
import MLC_evaluating_models from "./challenges/evaluating-models.json";
import MLC_gradient_descent from "./challenges/gradient-descent.json";
import MLC_k_means_clustering from "./challenges/k-means-clustering.json";
import MLC_k_nearest_neighbors from "./challenges/k-nearest-neighbors.json";
import MLC_linear_regression from "./challenges/linear-regression.json";
import MLC_logistic_regression from "./challenges/logistic-regression.json";
import MLC_ml_in_practice from "./challenges/ml-in-practice.json";
import MLC_neural_networks_basics from "./challenges/neural-networks-basics.json";
import MLC_overfitting_underfitting from "./challenges/overfitting-underfitting.json";
import MLC_types_of_ml from "./challenges/types-of-ml.json";
import MLC_what_is_ml from "./challenges/what-is-ml.json";

export const RAW_ML_CHALLENGES: Record<string, unknown> = {
  "data-and-features": MLC_data_and_features,
  "decision-trees": MLC_decision_trees,
  "evaluating-models": MLC_evaluating_models,
  "gradient-descent": MLC_gradient_descent,
  "k-means-clustering": MLC_k_means_clustering,
  "k-nearest-neighbors": MLC_k_nearest_neighbors,
  "linear-regression": MLC_linear_regression,
  "logistic-regression": MLC_logistic_regression,
  "ml-in-practice": MLC_ml_in_practice,
  "neural-networks-basics": MLC_neural_networks_basics,
  "overfitting-underfitting": MLC_overfitting_underfitting,
  "types-of-ml": MLC_types_of_ml,
  "what-is-ml": MLC_what_is_ml,
};
