// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import ML_data_and_features from "./lessons/data-and-features.json";
import ML_decision_trees from "./lessons/decision-trees.json";
import ML_evaluating_models from "./lessons/evaluating-models.json";
import ML_gradient_descent from "./lessons/gradient-descent.json";
import ML_k_means_clustering from "./lessons/k-means-clustering.json";
import ML_k_nearest_neighbors from "./lessons/k-nearest-neighbors.json";
import ML_linear_regression from "./lessons/linear-regression.json";
import ML_logistic_regression from "./lessons/logistic-regression.json";
import ML_ml_in_practice from "./lessons/ml-in-practice.json";
import ML_neural_networks_basics from "./lessons/neural-networks-basics.json";
import ML_overfitting_underfitting from "./lessons/overfitting-underfitting.json";
import ML_types_of_ml from "./lessons/types-of-ml.json";
import ML_what_is_ml from "./lessons/what-is-ml.json";

export const RAW_ML_LESSONS: Record<string, unknown> = {
  "data-and-features": ML_data_and_features,
  "decision-trees": ML_decision_trees,
  "evaluating-models": ML_evaluating_models,
  "gradient-descent": ML_gradient_descent,
  "k-means-clustering": ML_k_means_clustering,
  "k-nearest-neighbors": ML_k_nearest_neighbors,
  "linear-regression": ML_linear_regression,
  "logistic-regression": ML_logistic_regression,
  "ml-in-practice": ML_ml_in_practice,
  "neural-networks-basics": ML_neural_networks_basics,
  "overfitting-underfitting": ML_overfitting_underfitting,
  "types-of-ml": ML_types_of_ml,
  "what-is-ml": ML_what_is_ml,
};
