// Scans lib/lessons/*.json and lib/slides/*.json, validates that each parses,
// and (re)generates lib/generated-lessons.ts and lib/generated-slides.ts with
// static imports for every valid file. Invalid or missing files are skipped and
// reported; the content layer falls back gracefully for anything not present.
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(process.cwd());

function generate({ dir, outFile, exportName, idPrefix, validate }) {
  const files = fs.existsSync(dir)
    ? fs.readdirSync(dir).filter((f) => f.endsWith(".json"))
    : [];

  const valid = [];
  const invalid = [];

  for (const f of files) {
    const slug = f.replace(/\.json$/, "");
    try {
      const txt = fs.readFileSync(path.join(dir, f), "utf8");
      const parsed = JSON.parse(txt);
      const err = validate(parsed);
      if (err) {
        invalid.push({ slug, error: err });
        continue;
      }
      valid.push(slug);
    } catch (e) {
      invalid.push({ slug, error: String(e.message || e) });
    }
  }

  valid.sort();
  const idOf = (slug) => idPrefix + slug.replace(/[^a-zA-Z0-9]/g, "_");
  const rel = path.basename(dir);

  const imports = valid
    .map((s) => `import ${idOf(s)} from "./${rel}/${s}.json";`)
    .join("\n");
  const entries = valid.map((s) => `  ${JSON.stringify(s)}: ${idOf(s)},`).join("\n");

  const out = `// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
${imports}

export const ${exportName}: Record<string, unknown> = {
${entries}
};
`;
  fs.writeFileSync(outFile, out);

  console.log(`build: wrote ${valid.length} entries to ${path.basename(outFile)}`);
  if (invalid.length) {
    console.warn(`build: ${invalid.length} invalid/skipped in ${rel}:`);
    for (const i of invalid) console.warn(`  - ${i.slug}: ${i.error}`);
  }
}

generate({
  dir: path.join(root, "lib", "lessons"),
  outFile: path.join(root, "lib", "generated-lessons.ts"),
  exportName: "RAW_LESSONS",
  idPrefix: "L_",
  validate: (p) =>
    !p || typeof p !== "object" || !Array.isArray(p.blocks)
      ? "missing blocks array"
      : null,
});

generate({
  dir: path.join(root, "lib", "slides"),
  outFile: path.join(root, "lib", "generated-slides.ts"),
  exportName: "RAW_SLIDES",
  idPrefix: "S_",
  validate: (p) =>
    !p || typeof p !== "object" || !Array.isArray(p.slides)
      ? "missing slides array"
      : null,
});
