// Scans lib/lessons/*.json, validates that each parses, and (re)generates
// lib/generated-lessons.ts with static imports for every valid lesson file.
// Invalid or missing lessons are skipped and reported; the content layer
// falls back to a placeholder for any slug that isn't present.
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(process.cwd());
const dir = path.join(root, "lib", "lessons");
const outFile = path.join(root, "lib", "generated-lessons.ts");

const files = fs.existsSync(dir)
  ? fs.readdirSync(dir).filter((f) => f.endsWith(".json"))
  : [];

const valid = [];
const invalid = [];

for (const f of files) {
  const slug = f.replace(/\.json$/, "");
  try {
    const txt = fs.readFileSync(path.join(dir, f), "utf8");
    const parsed = JSON.parse(txt);
    if (!parsed || typeof parsed !== "object" || !Array.isArray(parsed.blocks)) {
      invalid.push({ slug, error: "missing blocks array" });
      continue;
    }
    valid.push(slug);
  } catch (e) {
    invalid.push({ slug, error: String(e.message || e) });
  }
}

valid.sort();

const idOf = (slug) => "L_" + slug.replace(/[^a-zA-Z0-9]/g, "_");

const imports = valid
  .map((s) => `import ${idOf(s)} from "./lessons/${s}.json";`)
  .join("\n");

const entries = valid.map((s) => `  ${JSON.stringify(s)}: ${idOf(s)},`).join("\n");

const out = `// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
${imports}

export const RAW_LESSONS: Record<string, unknown> = {
${entries}
};
`;

fs.writeFileSync(outFile, out);

console.log(`build-lessons: wrote ${valid.length} lessons to generated-lessons.ts`);
if (invalid.length) {
  console.warn(`build-lessons: ${invalid.length} invalid/skipped:`);
  for (const i of invalid) console.warn(`  - ${i.slug}: ${i.error}`);
}
