// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import HTML_forms_and_inputs from "./lessons/forms-and-inputs.json";
import HTML_headings_and_text from "./lessons/headings-and-text.json";
import HTML_how_the_web_works from "./lessons/how-the-web-works.json";
import HTML_html_document_structure from "./lessons/html-document-structure.json";
import HTML_images_and_media from "./lessons/images-and-media.json";
import HTML_links_and_navigation from "./lessons/links-and-navigation.json";
import HTML_semantic_html from "./lessons/semantic-html.json";
import HTML_what_is_html from "./lessons/what-is-html.json";

export const RAW_HTML_LESSONS: Record<string, unknown> = {
  "forms-and-inputs": HTML_forms_and_inputs,
  "headings-and-text": HTML_headings_and_text,
  "how-the-web-works": HTML_how_the_web_works,
  "html-document-structure": HTML_html_document_structure,
  "images-and-media": HTML_images_and_media,
  "links-and-navigation": HTML_links_and_navigation,
  "semantic-html": HTML_semantic_html,
  "what-is-html": HTML_what_is_html,
};
