// AUTO-GENERATED by scripts/build-lessons.mjs — do not edit by hand.
import HTMLC_forms_and_inputs from "./challenges/forms-and-inputs.json";
import HTMLC_headings_and_text from "./challenges/headings-and-text.json";
import HTMLC_how_the_web_works from "./challenges/how-the-web-works.json";
import HTMLC_html_document_structure from "./challenges/html-document-structure.json";
import HTMLC_images_and_media from "./challenges/images-and-media.json";
import HTMLC_links_and_navigation from "./challenges/links-and-navigation.json";
import HTMLC_semantic_html from "./challenges/semantic-html.json";
import HTMLC_what_is_html from "./challenges/what-is-html.json";

export const RAW_HTML_CHALLENGES: Record<string, unknown> = {
  "forms-and-inputs": HTMLC_forms_and_inputs,
  "headings-and-text": HTMLC_headings_and_text,
  "how-the-web-works": HTMLC_how_the_web_works,
  "html-document-structure": HTMLC_html_document_structure,
  "images-and-media": HTMLC_images_and_media,
  "links-and-navigation": HTMLC_links_and_navigation,
  "semantic-html": HTMLC_semantic_html,
  "what-is-html": HTMLC_what_is_html,
};
